version: '3.5'

services:
    nextcloud:
        image: nextcloud:${NEXTCLOUD_IMAGE_TAG}
        restart: always
        ports: 
            - ${NEXTCLOUD_PORT}:80
        volumes:
            - nextcloud:/var/www/html
        links:
            - psql
            - redis
        depends_on:
            - psql
            - redis
        environment: 
            - POSTGRES_DB=${PSQL_DATABASE}
            - POSTGRES_USER=${PSQL_USER}
            - POSTGRES_PASSWORD=${PSQL_PASSWORD}
            - POSTGRES_HOST=psql
            - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER}
            - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
            - NEXTCLOUD_DATA_DIR=/var/www/html/data
            - NEXTCLOUD_TRUSTED_DOMAINS=${NEXTCLOUD_TRUSTED_DOMAINS}
            - REDIS_HOST=redis
            - REDIS_HOST_PORT=6379
            - REDIS_HOST_PASSWORD=${REDIS_PASSWORD}
    psql: 
        image: postgres:${PSQL_IMAGE_TAG}
        restart: always
        environment: 
            - POSTGRES_USER=${PSQL_USER}
            - POSTGRES_PASSWORD=${PSQL_PASSWORD}
            - POSTGRES_DB=${PSQL_DATABASE}
        volumes: 
            - psql:/var/lib/postgresql/data

    redis:
      image: redis:${REDIS_IMAGE_TAG}
      restart: always
      command: redis-server --requirepass ${REDIS_PASSWORD}
      volumes:
        - redis:/data
        
volumes:
    nextcloud:
    psql:
    redis:
